project:
  type: book
  output-dir: _book

book:
  title: "BES Guide to Data Management"
  reader-mode: true
  
  page-footer:
    left: |
      BES Guide to Data Management (2nd edition) was edited by Natalie Cooper and Rob Barber.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://bes-guide.github.io/data-management/
  repo-url: https://github.com/BES-Guide/data-management
  repo-branch: main
  chapters:
    - index.qmd
    - introduction.qmd
    - planning.qmd
    - creating.qmd
    - processing.qmd
    - preserving.qmd
    - sharing.qmd
    - reusing.qmd
    - further-resources.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    code-link: true
    author-meta: "Natalie Cooper and Rob Barber"
    callout-appearance: simple
    number-depth: 3
