# Reusing {#sec-reusing}

Up to this point we have mostly assumed that you are collecting your own data, but what if you are reusing data that others collected? For the most part you should follow the instructions given in earlier sections: **no matter where data comes from, they still need to be considered throughout the data management process!**

Reuse of data falls into two main categories. First, and most common, is using additional (often large) datasets which contribute extra variables needed for your analyses. For example, you may have collected detailed data at several field sites, but want to use global climate data to extract temperature and precipitation values for your sites. In these cases, check the dataset you are using for details on how its authors want the data to be cited, and how you are allowed to share it. You should definitely cite the data in the main text of your paper to recognise the work that has gone into generating it. You should share only the subset of data you actually used, or a script showing how you extracted it. You should (generally) not redistribute the whole dataset if it does not belong to you (unless it comes with a license permitting this, see @sec-sharing: Licensing your data). Instead, refer to how others can access and download the data in your documentation. You should share as much of the data as you used in your analyses so people can repeat your results, unless the data has very strict limitations on what can be shared.

The second category is using data collected by others as part of a meta-analysis or synthesis. In this circumstance you must ensure that each piece of data you input can be traced back to its original source (see @sec-creating). In your publications you should cite each original dataset as a full reference in the methods section; not just a DOI or link in the methods or data availability statement. **Datasets deserve the same citation treatment as papers**. This is a formal requirement of the [PRISMA EcoEvo framework](https://www.prisma-statement.org/ecoevo) for systematic reviews and meta-analyses. Some additional considerations for collating data across species are described by Cooper & Freckleton 2026[^24] [here](LINK).

These guidelines can become complicated, however, in cases where you collect a dataset from the literature that uses hundreds or thousands of references, for example a large database of life history traits. In this situation, citing all the data references in the methods section will not be feasible (and is not allowed by many journals). A common solution is to provide all the data references used in the Supplemental Information and to refer to this in the methods. This is not ideal as individual publications containing the data do not gain citations, but currently no better universal solution exists. A possible stop-gap solution is to publish a pre-print on an established preprint server (e.g. [EcoEvoRxiv](https://ecoevorxiv.org/)) with all data references in the main text. These citations should be picked up by services like Google Scholar, even if the final version of the publication does not include all the references. A final option is to write a data paper (see @sec-sharing) describing your dataset with all data contributors as authors, for example the PREDICTS database[^25].

Whatever form reuse takes, the **key is transparency**. Throughout your papers, projects and documentation, make it clear whether the data you are using are newly generated, reused from an existing source, updated, or derived. This helps readers assess the independence of your results and gives proper credit to the original data collectors.

[^24]: Natalie Cooper and Rob P. Freckleton. 2026. Phylogenetic Comparative Methods: A Practical Introduction. DOI: 10.5281/zenodo.19222262.
[^25]: Hudson et al.